name: intrinsic-superclasses
version: '0.2.0.0'
synopsis: A quasiquoter implementation of the Intrinsic Superclasses Proposal
description: ! 'A template haskell implementation of the

  <https://ghc.haskell.org/trac/ghc/wiki/IntrinsicSuperclasses Intrinsic Superclasses
  Proposal>,

  which allows defining all superclass methods at the "root"

  of the class heirarchy in one declaration, rather than

  an instance declaration per class'
category: Language
author: Dai
maintainer: dailectic@gmail.com
copyright: Sodality
license: MIT
github: daig/intrinsic-superclasses
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5
- template-haskell
- haskell-src-meta
- containers
- mtl
library:
  source-dirs: src
  ghc-options: -Wall
