name: intrinsic-superclasses
version: '0.3.0.0'
synopsis: A quasiquoter for better instance deriving and default methods
description: ! 'A template haskell utility inspired by the

  <https://ghc.haskell.org/trac/ghc/wiki/IntrinsicSuperclasses Intrinsic Superclasses
  Proposal>,

  which allows defining all superclass methods at the "root" subclass

  of the heirarchy in one declaration, rather than

  an instance declaration per class.

  Also permits defining superclass method defaults with the subclass

  for greater flexibility than the DefaultSignatures extension'
category: Language
author: Dai
maintainer: dailectic@gmail.com
copyright: Sodality
license: MIT
github: daig/intrinsic-superclasses
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5
- template-haskell
- haskell-src-meta
- containers
- mtl
library:
  source-dirs: src
  ghc-options: -Wall
